### ISSUE TITLE
Doesn't support CSS Modules

### ISSUE THREAD

**Issue by es-repo** [jackmellis/require-extension-hooks-vue#18]
Unfortunately it doesn't support Vue SFC with CSS Modules. Do you have planes to add this?

**Comment by jackmellis** [comment]
I haven't played around with CSS Modules much, but it would be good to support it. I can have a look into when I next get a minute, or I'd welcome a PR :)

**Comment by es-repo** [comment]
Working on it. Wouldn't you mind if I refactor index.js a little bit?

**Comment by jackmellis** [comment]
Great! What did you have in mind?

**Comment by es-repo** [comment]
I'm going to process css-module styles with postcss+postss-modules to get json object with css classes and inject it into Vue component as computed property.

**Comment by es-repo** [comment]
Please check out the pull request.

**Comment by jackmellis** [comment]
@es-repo thanks a lot for this!

**Comment by es-repo** [comment]
You are welcome!
