### ISSUE TITLE
Vue development warning only if not requiring .vue files

### ISSUE THREAD

**Issue by Nicolaidavies** [jackmellis/require-extension-hooks-vue#21]
Hello, 

Background: I was setting up a test suite using ava, the recommended way to use vue + ava is to use this library.

During the setup I noticed that a Vue warning would popup if a test file does not require a `.vue` file or 'vue-test-utils` .

![screen shot 2017-09-22 at 13 21 59](https://user-images.githubusercontent.com/2064393/30742788-0f685352-9f9b-11e7-8669-de60804f7aac.png)

I have reproduced the bug in this repo: [https://github.com/Nicolaidavies/vue-test-utils-ava-example](https://github.com/Nicolaidavies/vue-test-utils-ava-example). 

Uncommenting the line that imports `vue-test-utils` in `test/specs/List.spec.js` makes the error go away. 

Please let me know if this is not the right place for this bug report.

- Nicolai

**Comment by jackmellis** [comment]
Yeah I don't think this is a problem with this particular library (it only compiles the vue files, it doesn't ever actually load or instantiate vue).

At a guess I would say something in vue-test-utils flips a switch to turn off this warning, but it isn't triggered if you don't use it, or something like that.

I would probably raise this in the vue-test-utils repo.

A quick fix is to use something like module-alias and route all vue requires to `vue/dist/vue.runtime.min.js` which would automatically supress this message.

**Comment by Nicolaidavies** [comment]
Thank your for your response. I'll raise the issue in `vue-test-utils`.
