### ISSUE TITLE
Doesn't seem to work with coffee?

### ISSUE THREAD

**Issue by stuta** [jackmellis/require-extension-hooks-vue#22]
Hello.

I was using this: https://medium.freecodecamp.org/how-to-write-blazing-fast-vue-unit-tests-with-tape-and-vue-test-utils-be069ccd4acf

My test.vue:

```vue
<template lang='pug'>
  span Hello from component test.
</template>

<script lang='coffee'></script>
export default {}
<style lang='stylus' scoped>
</style>
```

This gives an error: "Error: Unknown file extension .coffee"

**Comment by jackmellis** [comment]
Yes so rehv doesn’t handle other languages out of the box. If it encounters a `lang=“coffee”` it will attempt to look for a require-extension-hooks plugin for that filetype.

As far as I’m aware there isn’t currently a plugin for coffeescript (I think there’s a typescript plugin in progress already). I wouldn’t imagine it’s be hard to create one and I’d welcome any contributions!
