### ISSUE TITLE
How can I config it to work with typescript?

### ISSUE THREAD

**Issue by rafaesc** [jackmellis/require-extension-hooks-vue#23]
Hi,

Congratulations for your project, I had been searching something similar to this to integrate to my library, 
Only need to typescript support to finish it

````js
const hooks = require('require-extension-hooks');
hooks('vue').plugin('vue').push();
hooks(['vue', 'js']).plugin('babel').push();
hooks('ts');

let component = require('../tests/components/render-ts.vue');

console.log(component);
````

I don't know how add the transpiled
````
...\node_modules\babel-core\lib\transformation\file\index.js:590
      throw err;
      ^

SyntaxError: .../tests/components/render-ts.vue: Unexpected token (13:0)
  11 | import Component from "vue-class-component";
  12 |
> 13 | @Component({
     | ^
  14 |  name: 'Foot'
  15 | })
  16 | export default class Foot extends Vue {
````

Regards,

**Comment by jackmellis** [comment]
Yes this is something I had in mind (along with coffeescript). I created a repo a while back but haven't had the time to sort it out. I'd welcome any PRs to help support TS

https://github.com/jackmellis/require-extension-hooks-ts

**Comment by rafaesc** [comment]
I would like to do, but I need to understand your library, and maybe it takes time to develop a typescript support. For now, only I will integrate this library, thanks.
