### ISSUE TITLE
Source map not used in stack trace

### ISSUE THREAD

**Issue by eddyerburgh** [jackmellis/require-extension-hooks-vue#24]
Hi @jackmellis , hope you're well.

Source maps produced by require-extension-hooks aren't used in the stack trace. It would be great if we could fix this issue.

**Comment by jackmellis** [comment]
This has come up before, I was thinking of creating a separate module to incorporate this (to help keep basic overheads down), but with work commitments (and specifically non-vue work commitments) some of my plans have been put aside for a while.

Is there a simple solution to get this in place?

**Comment by jackmellis** [comment]
for reference: https://github.com/jackmellis/require-extension-hooks-vue/issues/17
