### ISSUE TITLE
Non Self-Closing Script Tags Do Not Work

### ISSUE THREAD

**Issue by Gregoyle** [jackmellis/require-extension-hooks-vue#25]
Including the Vue Component in a JS file in a .vue doesn't work if it's not a self-closing tag.
So, `<script src="List.js" />` works while `<script src="List.js"></script>`  does not. It may be intentional but it tripped me up hard. I have a small example project which demonstrates this:

https://github.com/Gregoyle/Ava_Vue_Multi_File_Fail/blob/master/src/components/List.vue

**Comment by jackmellis** [comment]
@Gregoyle I've published a fix for this issue this morning
