### ISSUE TITLE
Simply requiring this module breaks ts-node w/mocha 😿

### ISSUE THREAD

**Issue by snaptopixel** [jackmellis/require-extension-hooks-vue#30]
I've got a working test config using mocha with ts-node to run tests written in typescript. I was hoping to add .vue files to the mix using this module but the second I require it, all the tests fail.

**Comment by jackmellis** [comment]
:anguished: Do the tests fail with any sort of useful error stack?

**Comment by snaptopixel** [comment]
Hey @jackmellis thanks for the response! Looks like this is related to vue-template-compiler, I required it directly and had the same errors. Closing, cheers!
