### ISSUE TITLE
TypeError: Super Expression must either be null or a function

### ISSUE THREAD

**Issue by dhershman1** [jackmellis/require-extension-hooks-vue#40]
I don't know if this issue falls on this module, on prettier, or on the component-compiler-utils ?

It seems like when attempting to run anything through the hooks you get this error (this was pulled directly from this modules unit tests)

```
TypeError: Super expression must either be null or a function
    ----------------------------------------------------------------
      name: TypeError
      message: Super expression must either be null or a function
      at: '_inherits (node_modules/prettier/index.js:1957:11)'
```

It looks like Prettier might be causing the underlying issue though. So I am unsure at this point of what this falls under or a proper work around.

**Comment by jackmellis** [comment]
looks like this is an issue with prettier that's been brought up by a few others. Take a look [here](https://github.com/vuejs/vue-cli/issues/2128), I hope that helps
