### ISSUE TITLE
(intermediate value) is not a function

### ISSUE THREAD

**Issue by syropian** [jackmellis/require-extension-hooks-vue#5]
I'm attempting to use this so I can easily test Vue components with Ava. I made a very simple test component:

```
<template>
  <div class="foo-component">Hi!</div>
</template>
<script>
export default {
  name: 'Foo'
}
</script>
```

It looks like the hook compiles it to this (I unminified it a bit for readability):

```
(module.exports.default || module.exports).render = function() {
    var _vm = this;
    var _h = _vm.$createElement;
    var _c = _vm._self._c || _h;
    return _c('div', {
        staticClass: "foo-component"
    }, [_vm._v("Hi!")])
};
```

but I always get an `(intermediate value) is undefined` error.

```
TypeError: (intermediate value) is not a function
    at Object.<anonymous> (/Users/user/Sites/vue-tagger/src/Foo.vue:4:1)
    at Module._compile (module.js:571:32)
    at hook (/Users/user/Sites/vue-tagger/node_modules/require-extension-hooks/hook.js:43:10)
```

Any ideas? Would love to get this working so I don't have to resort to vue-node and webpack for simple component testing.

**Comment by jackmellis** [comment]
If you stick a semi colon after your export does that work?
```javascript
<script>
export default {
 /* ... */
};
</script>
```

I think it may be as simple as the render function being too close to the export...

**Comment by jackmellis** [comment]
Yeah effectively this is producing something like:
```javascript
export default {}(module.exports.render=/*...*/)
```
which is not valid js. I'll fix and update the npm package.

Thanks.
