### ISSUE TITLE
Load scripts from external source

### ISSUE THREAD

**Issue by jackmellis** [jackmellis/require-extension-hooks-vue#8]
Where script tag is `<script src="./url-of-my-script.js"/>`

**Comment by jackmellis** [comment]
#2

**Comment by Gregoyle** [comment]
I just noticed that this doesn't work when you have opening and closing script tags, only when you have a single self-closing script tag.

**Comment by jackmellis** [comment]
Thanks, I'll look into it. I'm assuming vue-loader handles it correctly?
